-- MySQL Script generated by MySQL Workbench
-- Tue Jul  3 22:50:36 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Kunde`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Kunde` (
  `id` INT NOT NULL,
  `vorname` VARCHAR(45) NULL,
  `nachname` VARCHAR(45) NULL,
  `strasse` VARCHAR(45) NULL,
  `ort` VARCHAR(45) NULL,
  `plz` VARCHAR(45) NULL,
  `tel` VARCHAR(45) NULL,
  `kundeSeit` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bestellung`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bestellung` (
  `id` INT NOT NULL,
  `Kunde_id` INT NOT NULL,
  `datum` TIMESTAMP NULL,
  `bemerkungen` VARCHAR(255) NULL,
  PRIMARY KEY (`id`, `Kunde_id`),
  INDEX `fk_Bestellung_Kunde_idx` (`Kunde_id` ASC),
  CONSTRAINT `fk_Bestellung_Kunde`
    FOREIGN KEY (`Kunde_id`)
    REFERENCES `mydb`.`Kunde` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Artikel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Artikel` (
  `id` INT NOT NULL,
  `bezeichnung` VARCHAR(45) NULL,
  `preis` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BestellPosition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BestellPosition` (
  `id` INT NOT NULL,
  `Bestellung_id` INT NOT NULL,
  `Artikel_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Bestellung_id`, `Artikel_id`),
  INDEX `fk_BestellPosition_Bestellung1_idx` (`Bestellung_id` ASC),
  INDEX `fk_BestellPosition_Artikel1_idx` (`Artikel_id` ASC),
  CONSTRAINT `fk_BestellPosition_Bestellung1`
    FOREIGN KEY (`Bestellung_id`)
    REFERENCES `mydb`.`Bestellung` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BestellPosition_Artikel1`
    FOREIGN KEY (`Artikel_id`)
    REFERENCES `mydb`.`Artikel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inhalt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Inhalt` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `preis` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Konfiguration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Konfiguration` (
  `Artikel_id` INT NOT NULL,
  `Inhalt_id` INT NOT NULL,
  PRIMARY KEY (`Artikel_id`, `Inhalt_id`),
  INDEX `fk_Artikel_has_Inhalt_Inhalt1_idx` (`Inhalt_id` ASC),
  INDEX `fk_Artikel_has_Inhalt_Artikel1_idx` (`Artikel_id` ASC),
  CONSTRAINT `fk_Artikel_has_Inhalt_Artikel1`
    FOREIGN KEY (`Artikel_id`)
    REFERENCES `mydb`.`Artikel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Artikel_has_Inhalt_Inhalt1`
    FOREIGN KEY (`Inhalt_id`)
    REFERENCES `mydb`.`Inhalt` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BestellteKonfiguration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BestellteKonfiguration` (
  `BestellPosition_id` INT NOT NULL,
  `Inhalt_id` INT NOT NULL,
  PRIMARY KEY (`BestellPosition_id`, `Inhalt_id`),
  INDEX `fk_BestellPosition_has_Inhalt_Inhalt1_idx` (`Inhalt_id` ASC),
  INDEX `fk_BestellPosition_has_Inhalt_BestellPosition1_idx` (`BestellPosition_id` ASC),
  CONSTRAINT `fk_BestellPosition_has_Inhalt_BestellPosition1`
    FOREIGN KEY (`BestellPosition_id`)
    REFERENCES `mydb`.`BestellPosition` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BestellPosition_has_Inhalt_Inhalt1`
    FOREIGN KEY (`Inhalt_id`)
    REFERENCES `mydb`.`Inhalt` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
