DROP TABLE EO_PK_TABLE CASCADE;

DROP TABLE Artikel CASCADE;

DROP TABLE BestellPosition CASCADE;

DROP TABLE BestellteKonfiguration CASCADE;

DROP TABLE Bestellung CASCADE;

DROP TABLE Inhalt CASCADE;

DROP TABLE Konfiguration CASCADE;

DROP TABLE Kunde CASCADE;

CREATE TABLE Artikel (bezeichnung VARCHAR(50) NOT NULL, id INT NOT NULL, preis DECIMAL(38,4) NOT NULL);

CREATE TABLE BestellPosition (artikelID INT, bestellungID INT NOT NULL, id INT NOT NULL);

CREATE TABLE BestellteKonfiguration (bestellPositionId INT NOT NULL, inhaltId INT NOT NULL);

CREATE TABLE Bestellung (bemerkungen VARCHAR(50) NOT NULL, datum DATE NOT NULL, id INT NOT NULL, kundeID INT NOT NULL);

CREATE TABLE Inhalt (id INT NOT NULL, name VARCHAR(50) NOT NULL, preis DECIMAL(38,4) NOT NULL);

CREATE TABLE Konfiguration (artikelId INT NOT NULL, inhaltId INT NOT NULL);

CREATE TABLE Kunde (id INT NOT NULL, kundeseit DATE NOT NULL, nachname VARCHAR(50) NOT NULL, ort VARCHAR(50) NOT NULL, plz VARCHAR(50) NOT NULL, strasse VARCHAR(50) NOT NULL, tel VARCHAR(50) NOT NULL, vorname VARCHAR(50) NOT NULL);

CREATE TABLE EO_PK_TABLE (NAME CHAR(40) PRIMARY KEY, PK INT);

ALTER TABLE Artikel ADD PRIMARY KEY (id);

ALTER TABLE BestellPosition ADD PRIMARY KEY (id);

ALTER TABLE BestellteKonfiguration ADD PRIMARY KEY (bestellPositionId, inhaltId);

ALTER TABLE Bestellung ADD PRIMARY KEY (id);

ALTER TABLE Inhalt ADD PRIMARY KEY (id);

ALTER TABLE Konfiguration ADD PRIMARY KEY (artikelId, inhaltId);

ALTER TABLE Kunde ADD PRIMARY KEY (id);

